@startuml
User -> Sender: replay
Sender-> ReceiverApp: session.loadMedia(req)
ReceiverApp->ReceiverApp: onLoad(req)
ReceiverApp -> RemotePlayer: vdp.sendNotification('doPlay')
RemotePlayer --> Sender: play
@enduml